### ISSUE TITLE
Infantry uniforms can be seen skinned incorrectly

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#429]
Originally reported by: **Andrew Theel (Bitbucket: [AndrewTheel](http://bitbucket.org/AndrewTheel), GitHub: [AndrewTheel](http://github.com/AndrewTheel))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/430

**Comment by dynamittt** [comment]
Get rid of UPL crap system. Just remove it.
Do all of the stuff inside Pawn class.
This is what I tried...
Using a parent class for each Unit type, for a German Autumn Rauchtarn  (just to serve as an example).
Use a custom function that will assign a mesh randomly from an array of available meshes (depending on the units!)
Depending on the mesh selected, select the appropriate texture randomly from a list of available BodySkins.
Depending on the body skin selected, assign the appropriate SleeveTexture for first-person arms.
And also assign the proper HeadGear color/skin (camo) to match the BodySkin camo/color/tan.
And assign a random FaceSkin from a list of available ones for this Pawn.

This way: you save your time from having to write a single UPL record for all the possible FaceSkin combinations. Or a single pawn for all the possible variations of meshes, bodyskins and etc. etc...  
Save your time from having to write Role classes......
Problem is the vanilla code needs static functions to work, see ROPlayer, function SetPawnClass (DynamicLoadObject), ROTeamGame: function SetCharacter, ROPawn function Setup.... Static functions don't like dynamic stuff.
The one who manages to do this should receive an award.
Good luck.

**Comment by cmbasnett** [comment]
Fixed in commit 6eaf4ca0ddb6b934478b6dc6562290f2e7fbdf64.

**Comment by handsm** [comment]
Re-opened as this is still a problem, even with recent dev build changes made to move away from the PlayerRecord/.upl player character setup system. I can recreate it fairly easily by setting up a bad network environment (high ping & some packet loss).

But I've found 2 separate causes of the bug and verified that they sometimes do make it happen. I have fixed both and should be committing soon. Hopefully that will cure it once and for all. The problem is a replication timing issue, as is so often the case.

**Comment by handsm** [comment]
This is all about the PlayerRecord (PR) system of setting up player character models from .upl files. Even in the current dev build, where Theel has removed use of upl files, this enemy uniform bug still happens, because the heart of the PR system is still there and is still bugged. So first we have to understand the PR system:

### How the PlayerRecord/upl system works

At its heart is the CharacterName (CN) variable in the PlayerReplicationInfo (PRI) class. This is a string that corresponds with (i) the list of Models in the default props of a RoleInfo (RI) and (ii) matching character models in the upl files. It is selected randomly on the server from the RI's Models array and replicates to all clients, which then need to set up the player model from the corresponding upl line.

This system is fundamentally flawed because players can edit their local upl files, which are not controlled by the server. But that is a totally separate issue and I won't cover it here. That is the real driver behind replacing the PR system and the upl files.

The PR system is based on the PR struct, defined in the UT2004 'xUtil' class, which is not an actor. There is a lot of native in there, the most important of which is the FindPlayerRecord() function, which checks upl files, finds a record that matches the passed in CN string, then populates a PR struct from the upl line. This function is used in various classes to get the player's PR (usually known as a 'Rec' variable) and use it to set up various player model stuff.

A PR struct contains, or may contain, a wide range of player setup info. But the most relevant are the player's mesh and body & face skins. The defined Species class, which is an abstract object, can also be important. But it will never vary within a given RI so it doesn't actually need to be set from the PR.  'Species' demonstrates this has UT2004 roots. The system is maintained in RO, but in DH species has effectively become 'nationality' (my gut feeling is these add little). I suspect the basis of the PR system was to allow localised custom appearances for players, but it is at odds with RO/DH.

The key player set up functionality is in the Setup() functions in the ROPawn class and the Species class. The ROPawn function is called first and it calls the static function in Species.

### So, where/how does it go wrong?

It's all about how a net client implements the CN it receives from the server, i.e. how, and crucially WHEN, it sets up the player using that info. I have found and confirmed two separate bugs that both occur occasionally, more so in a poor network environment, and cause the uniform bug. One also causes other serious bugs. The first is a network replication timing issue - the source of so many long-standing, sporadic issues - that isn't handled properly in code. The second is just plain bad implementation in an RO class.

Things have the potential to go wrong right from the start, because the PRI's CN is initialised from the local DarkestHourUser.ini file. It is set from the 'Character' entry in the [DefaultPlayer] section. Our own DH DefUser.ini file has this set to 'G_Heer1', the same as in RO. As everyone's DHUser files are initially built from the default .ini, most people will have this. G_Heer1 is a German player model from the RO.upl file. The PR system needs to override this with the relevant CN, selected by the server from the RI's Models array. When it fails to do so we get the uniform bug.

G_Heer1 in the .ini is why this bug usually manifests itself as an allied player appearing as a German. It happens just as often on the German team, but isn't so visible. G_Heer1 is obsolete in DH; it does not appear in DH upl files. The fact that it gets used demonstrates that the native PR system searches all upl files, including any in the RO/System folder. Specifically, the native function FindPlayerRecord() must do that. G_Heer1 uses the RO player characters animation file, which lacks all DH-specific animations. So although the uniform bug may not be as visible in the German team, if you had a client log window running while playing, you would see it spam lots of missing anim errors.

You can in fact change your .ini file to have a different default Character. When testing this I specified an RO Soviet winter player model, which made the bug extremely easy to spot on either team!

So the bottom line is the client must set up the player's model when it receives the updated CN from the server, i.e. a model that is valid for the player's role. Note that in the current dev build, with upl files and the Models array removed, the client still receives an updated CN and must act on it, it's just that the updated CN is now null. But the client still needs to override the default initialisation of G_Heer1 or whatever from the User.ini file.

Stripping it down, to set up the player we need his pawn and his PRI, and the PRI must have its RI and updated CN. To me, the logical step would be to use the PRI to trigger player setup, when it receives a new CN. And there is native PostNetReceive (PNRec) functionality in PRI to detect a new CN, which calls the UpdateCharacter() on a net client (note the apparently unused OldCharacterName variable in PRI, which is actually being used by native to detect a changed value). But all UpdateCharacter() does is set the PRI's 'Rec' variable, which is a PR, from the new CN. The PRI passively waits for something else to do the setup. The problem is the PRI doesn't have a reference to the player's pawn, although it could and probably should have. But it doesn't and so generally the system relies on the ROPawn's PNRec event, in the bInitializedPlayer section, which calls Setup().

### Uniform bug cause no. 1

In ROPawn's PNRec there are 3 possible triggers there. The 1st can be ignored because ForceDefaultCharacter() is always false. The 2nd trigger is the main one and will mostly work ok. It is triggered when the pawn has received its PRI and the PRI has its RI and the PRI's CN has been updated - that last check is critical. The check is that the RI's GetModel() function matches the PRI's CN, i.e. is the CN valid for the role. Although it is flawed - we'll come back to that - it basically does the job, which is making sure the bInitializedPlayer section isn't triggered and 'shut down' until we have the updated CN. That brings us to the 3rd and final trigger, which causes the uniform bug!

The ROPawn.PNRec author was smart enough to realise/notice that sometimes a pawn received through replication may be in a vehicle, in which case the player won't be controlling their ROPawn, so it won't have a PRI. On entering any vehicle position the PRI reference gets transferred to the vehicle pawn. The vehicle is recorded as DrivenVehicle in the ROPawn, so the 3rd trigger checks for (DrivenVehicle != none && DrivenVehicle.PRI != none). But it doesn't have the same check that the CN has been updated. So if the PRI's CN hasn't been updated yet, but the ROPawn receives a DrivenVehicle.PRI, it sets up the player model (again) from the initialised G_Heer1 or whatever model. Then it sets bInitializedPlayer=true, so when the real, updated CN arrives on the PRI, nothing happens and we are stuck with the uniform bug.

The fix for this is simply adding the same check that the CN has been updated, when the player is in a vehicle. I suspect this is why we've seen a large increase in the uniform bug since DH v6, because the new deploy system means that clients receive replicated players that are in vehicles much more often.

### Uniform bug cause no. 2

The uniform bug can't only be from players being in vehicle when replicated. We've all seen players spawn on foot with the wrong uniform. The 2nd bug is caused by ROPawn's NotifyTeamChanged() function, which is intended to handle player set up in exactly the same that PNRec does. It can be called from the PRI's PNRec event, in its bTeamNotified section. When the PRI receives its replicated 'Team' actor reference, it checks whether its own player's pawn has been received yet on the client, using a foreach iteration. If it does then it calls NotifyTeamChanged() on the pawn.

Note that it also looks for any other actors that want to be notified of a team change, but since no actors have bNotifyLocalPlayerTeamReceived=true this is irrelevant. Actually, this whole bTeamNotified functionality seems odd, since it only happens once and if the player changes teams it doesn't happen again (the player's PRI persists throughout the round and is not re-spawned or re-initialised when he is killed or changes teams). I guess the idea of triggering our own pawn's set up here is if we've got it then we may as well try to set it up right now, instead of waiting for the pawn to trigger it by receiving the PRI. To me it seems pretty pointless, as if the PRI is on the client then the pawn will have its PRI reference & so will be doing this anyway. I suspect it's only being done because we're finding all actors to check for bNotifyLocalPlayerTeamReceived, so we may as well handle our own pawn, if we find it. Without the all actors iteration, which is actually pointless because bNotifyLocalPlayerTeamReceived isn't used, it's probably pointless to look for our own pawn here. Probably better just to leave it to the pawn to handle. Anyway ...

Due to replication timing, this functionality rarely finds the PRI's 'own' ROPawn, but occasionally it does and that's when we may get the uniform bug. ROPawn is a replacement for UT2004's 'XPawn' class. XPawn is deprecated/bypassed in RO, but some of the functionality has been copied into ROPawn, then parts have been modified. XPawn's PNRec event only handled the bInitializedPlayer functionality, then it disabled PNRec by setting bNetNotify=false. Since NotifyTeamChanged() is supposed to do exactly the same thing, in XPawn it simply called PNRec to avoid repeated the same code. Meaning NotifyTeamChanged() would end up disabling any further PNRec events if it managed to set up the player. All good - in XPawn at least.

It goes horribly wrong in ROPawn. Its PNRec is extended to include sections relating to bRecievedInitialLoadout and bInitializedWeaponAttachment. Because of that it only disables further PNRec events if all three sections have been flagged as complete. Someone writing ROPawn realised that NotifyTeamChanged() could no longer simply call PNRec, because that had been extended and now did other stuff (although tbh it would have been harmless and would have worked ok). So they re-stated NotifyTeamChanged() with the original player set up functionality from XPawn's PNRec, thinking it would do the same job. But unfortunately without considering any of the functionality changes in ROPawn!

Two problems there - big problems. Firstly, it doesn't include the crucial check that the PRI's CN has been updated. This affects a player on foot, not just one who spawns on the client while in a vehicle. So if replication timing means the PRI hasn't received its updated CN for the role, we get the uniform bug, even for a footslogger. Secondly the functionality still simply disables the pawn's PNRec if player set up is done, without considering whether the crucial bRecievedInitialLoadout and bInitializedWeaponAttachment functionality has been done. So as well as the uniform bug, we could also suffer the 'can't switch weapons' bug and some kind of messed up weapon attachment. Oh dear!

If we keep the NotifyTeamChanged() functionality, the fix is simply to make it do exactly the same as our soon-to-be-fixed player set up functionality in DHPawn's PNRec.

### Other issues

I mentioned the crucial check that the PRI's CN has been updated, which (when actually included) is currently handled by checking the RI's GetModel() function matches the PRI's CN. Although this works, in a very crude fashion, it is totally wrong to use this as a check on a client. GetModel() can only be used as an authority role function, because it makes a random selection from the RI's Models array. On a net client, when checking the PRI's CN has been updated for its player role, what we need to do is check whether the CN is valid for that role, which basically means checking whether it is ANY one of the specified Models. Or in the current dev build, stripped of Models and upl files, that CN is null (if there is no Models array).

On a client GetModel() gives PNRec one random section from the Models array and hopes it matches the PRI's CN. If it doesn't then the player isn't set up and the ROPawn waits for PNRec to get called again, at which point it rolls the die again and hopes to get a match. Only the arrival of the PRI reliably triggers PNRec in a timely fashion. After that, any subsequent triggering of PNRec is essentially random, relying on other updated replicated variables being received. We clearly need a new client function to check the validity of a CN vs the player's role.

A similar problem presents itself even in our fully fixed pawn's PNRec, as it has to check both that it has its PRI and that the PRI has its RI. The pawn may have its PRI but the PRI may not yet have its RI. In which case our only reliably timely call to PNRec (when the PRI was received) will do nothing and is gone. We're then waiting for a random re-triggering of PNRec by some other, unrelated variable. Not ideal.

Here endeth the saga. Everything you ever wanted to know - and probably a lot more - about the PlayerRecord/.upl system! Next the fixes .......

**Comment by handsm** [comment]
Bug no. 1 fixed in above commit.

**Comment by handsm** [comment]
In commit above I've added a new IsValidCharacterName() function in the RoleInfo, to replace the really bad use of GetModel() mentioned above.

**Comment by handsm** [comment]
Bug no.2 fixed in above commit.

Have moved the player model set up functionality into a new function called SetUpPlayerModel(), just to avoid code repetition, as can be called from either PostNetReceive() or the just fixed NotifyTeamChanged() function.

I'm pretty hopeful these fixes will now resolve the long-standing, but now much more prevalent, uniform bug. I'm certainly confident they fix the two separate sources of the bug I've traced & verified. So we can probably finally close this issue.

**Comment by handsm** [comment]
Closed as believed fixed. We can re-open if testing shows otherwise.
